Import("*")

addressing = env.WeaverAddressing(direct=True)
weaver = env.WeaverIguanaProgram(addressing = addressing)

sources=Split("sosh.c m5bench.c pt_test.c")
obj = env.KengeProgram("sosh", source=sources, weaver=weaver, LIBS=["c", "l4", "sos"])

Return("obj")

# vim: set filetype=python:
