Import("*")

addressing = env.WeaverAddressing(direct=True)
weaver = env.WeaverIguanaProgram(addressing = addressing)
sources=Split("sosh.c")
obj = env.KengeProgram("sosh", sources, weaver=weaver, LIBS=["c", "l4", "sos"])

Return("obj")

# vim: set filetype=python:
