Import("*")

addressing = env.WeaverAddressing(direct=True)
weaver = env.WeaverIguanaProgram(addressing = addressing)

sources=Split("pt_test.c")
obj = env.KengeProgram("pt_test", source=sources, weaver=weaver, LIBS=["c", "l4", "sos"])

Return("obj")

# vim: set filetype=python:
